### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by delta4d** [delta4d/fff#1]
- [x] fuzzy match algorithm
- [ ] a scoring algorithm
- [x] match characters highlighting
- [x] error handling
- [ ] test
- [x] at least add an option to show help, for f**k's sake
- [x] readme is tooooo simple, talking something concrete and useful
- [x] page scroll
- [ ] integrate with vim
- [ ] add man page
- [ ] split different structs into different headers
